# Apply to your cf-deployment based Cloud Foundry
#
# UAA client for notifications
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/notifications?
  value:
    override: true
    authorities: cloud_controller.admin,scim.read
    authorized-grant-types: client_credentials
    secret: "((uaa_clients_notifications_secret))"
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/notifications-admin?
  value:
    override: true
    authorities: notifications.manage,notifications.write,notification_templates.write,notification_templates.read,critical_notifications.write
    authorized-grant-types: client_credentials
    secret: "((uaa_clients_notifications_admin_secret))"
- type: replace
  path: /variables/-
  value:
    name: uaa_clients_notifications_secret
    type: password
- type: replace
  path: /variables/-
  value:
    name: uaa_clients_notifications_admin_secret
    type: password
