# Apply to your cf-deployment based Cloud Foundry
#
# UAA client for notifications
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/notifications?
  value:
    override: true
    authorities: cloud_controller.admin,scim.read
    authorized-grant-types: client_credentials
    secret: "((uaa_clients_notifications_secret))"

- type: replace
  path: /variables/-
  value:
    name: uaa_clients_notifications_secret
    type: password
